version: '3.1'

services:
  nginx:
    image: nginx
    volumes:
      - /opt/track/nginx/app.conf:/etc/nginx/conf.d/app.conf
      - /opt/track/nginx/.htpasswd:/etc/nginx/.htpasswd
      - /opt/track/letsencrypt:/etc/letsencrypt
      - /opt/track/www:/var/www
    ports:
      - 80:80
      - 443:443
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - /opt/track/mysql:/var/lib/mysql
  track-ui:
    image: beaugrantham/track-ui
    volumes:
      - /opt/track/www/media:/tmp/media
  track-api:
    image: beaugrantham/track-api
